### PR TITLE
[fork] initial habitization of foulkon-worker

### PR DESCRIPTION
**Pull request by srenatus**
Missing bits and pieces (not necessarily the next thing to work on,
though):

- figure out a way to use worker OR proxy from this habitat artifact
  (both binaries are built)
- I'd have liked to just put {{toToml cfg}} in
  habitat/config/worker.toml, but I didn't get this to work at all. So
  now, it's templated TOML we'll use for worker.toml.
- Haven't touched habitat/config/proxy.toml at all
- push docker image to dockerhub

Run this:

- hab studio enter
  - build
  - hab pkg export docker $HAB_ORIGIN/foulkon
- (outside of hab studio)
  - start some postgres: docker run --name foulkon-postgres -e POSTGRES_PASSWORD=superuser_password -e POSTGRES_USER=superuser_name -e POSTGRES_DB=foulkon -p 5432:5432 -d postgres:9
  - start worker: docker run --link foulkon-postgres:postgres -p 8000:8000 $HAB_ORIGIN/foulkon
  - query worker: curl -u admin:admin http://localhost:8000/api/v1/users

### CODE REVIEW

**Comment by srenatus** [comment]
~making this database-binding aware~ making PG configurable, will put it into a2 together with postgres.

**Comment by tylercloke** [comment]
Should this code just live in `authz-service`? Having it in our fork feels strange to me.

**Review by tylercloke — APPROVED** [review]
Looks good as a first pass, but I feel like merging this into the fork itself is a bit strange. We can have more than one habitat service in a repo if we need it :)

**Comment by srenatus** [comment]
@tylercloke I've discussed this with @chris-rock, again, too. Since I'm having trouble building the plan if it lives somewhere else (it's not terrible, just a hassle), the way forward will be:
1. get our _code changes_ merged upstream
2. tear the `habitat/` folder _out of here_ and put it in `chef/authz-service`.

We can then retire this repo. I'll see if I can get this merged upstream ASAP. In the meantime, let's keep rolling. I'll merge this.

**Pull request merged**
